package parser

import (
	"bufio"
	"bytes"
	"encoding/json"
	"io"
	"strings"
	"time"

	"github.com/dougdomingos/test-prettify/internal/model"
)

// testEvent represents a single event within the JSON file generated by Go's
// test tool.
type testEvent struct {

	// Time is the instant when the event is emmited.
	Time time.Time `json:"Time"`

	// Action refers to the type of event (ex: "start", "run", "pass", "fail").
	Action string `json:"Action"`

	// Package indicates the package to which the emmited event belongs.
	Package string `json:"Package"`

	// Test refers to the name of the test function associated with the event. May
	// not exist on some event types (ex: "start")
	Test string `json:"Test"`

	// Elapsed informs the total execution time of a test, in seconds. Only
	// present in final event types (ex: "pass", "fail")
	Elapsed float64 `json:"Elapsed"`

	// Output holds any logs produced by a event.
	Output string `json:"Output"`
}

// IsTest indicates whether the event is belongs to a test or package. It is
// used to distinguish non-test-related events from build errors or other
// outputs from Go's test tool.
func (t *testEvent) IsTest() bool {
	return t.Package != "" || t.Test != ""
}

// ParseTestJSON reads a stream of JSON entries, produced by Go's test tool,
// and returns the test results structured by package.
func ParseTestJSON(r io.Reader) (map[string]*model.TestPackage, error) {
	packages := make(map[string]*model.TestPackage)
	tests := make(map[string]*model.Test)
	outputs := make(map[string]*strings.Builder)

	statusMap := map[string]model.TestResult{
		"pass": model.TestPassed,
		"fail": model.TestFailed,
		"skip": model.TestSkipped,
	}

	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024) // set buffer max size to 1MB for test logs

	for scanner.Scan() {
		line := scanner.Bytes()

		if len(bytes.TrimSpace(line)) == 0 {
			// ignores empty rows within the JSON file
			continue
		}

		var event testEvent
		if err := json.Unmarshal(line, &event); err != nil || !event.IsTest() {
			// ignores malformed JSON and entries unrelated to tests
			continue
		}

		key := event.Package + "::" + event.Test

		if _, ok := packages[event.Package]; !ok {
			packages[event.Package] = model.NewTestPackage(event.Package)
		}

		if event.Output != "" {
			// accumulates the output generated by a specific test to build a single
			// string at its final state
			if _, ok := outputs[key]; !ok {
				outputs[key] = &strings.Builder{}
			}

			outputs[key].WriteString(event.Output)
		}

		switch event.Action {
		case "run":
			tests[key] = &model.Test{Name: event.Test}
		case "pass", "fail", "skip":
			if _, ok := tests[key]; !ok {
				// ensures subtests, which don't emit a "run" event, are correctly
				// registered
				tests[key] = &model.Test{Name: event.Test}
			}

			t := tests[key]
			t.ElapsedTime = event.Elapsed
			t.Status = statusMap[event.Action]

			if outputBuilder, ok := outputs[key]; ok {
				t.Output = outputBuilder.String()
			}

			packages[event.Package].InsertTest(t)
		}
	}

	return packages, scanner.Err()
}
